'use client';

import React from 'react';
import { useFarm } from '../../context/FarmContext';
import { StatusBadge } from '../common/StatusBadge';
import { CheckSquare, AlertTriangle, Droplets, Sprout, TrendingUp, CheckCircle2, Circle } from 'lucide-react';

export const ActionPlanView: React.FC = () => {
  const { actionPlan, toggleActionComplete, showToast } = useFarm();

  return (
    <div className="space-y-6 animate-fadeIn pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200/80 pb-4">
        <div>
          <span className="text-[10px] font-extrabold uppercase tracking-wider bg-emerald-100 text-emerald-900 px-2.5 py-0.5 rounded-full border border-emerald-200">
            OPERATIONAL DIRECTIVES
          </span>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight mt-1">
            Today's Farm Action Plan
          </h2>
          <p className="text-xs text-slate-500 font-medium">
            Prioritized tasks generated by KisanTwin AI based on live sensor telemetry and risk forecasts.
          </p>
        </div>

        <div className="flex items-center space-x-2 text-xs bg-emerald-50 border border-emerald-200 text-emerald-900 font-black px-3.5 py-2 rounded-2xl">
          <CheckSquare className="w-4 h-4 text-emerald-600" />
          <span>{actionPlan.filter((a) => !a.completed).length} Tasks Remaining</span>
        </div>
      </div>

      {/* Action Task Cards List */}
      <div className="space-y-4 max-w-4xl">
        {actionPlan.map((item) => (
          <div
            key={item.id}
            className={`bg-white rounded-3xl p-6 border transition-all shadow-xs space-y-3 ${
              item.completed
                ? 'opacity-60 bg-slate-50 border-slate-200'
                : item.category === 'URGENT'
                ? 'border-rose-300 ring-1 ring-rose-300/50'
                : 'border-slate-200'
            }`}
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <span
                  className={`text-[10px] font-black uppercase px-2.5 py-0.5 rounded-full ${
                    item.category === 'URGENT'
                      ? 'bg-rose-600 text-white'
                      : item.category === 'WATER'
                      ? 'bg-cyan-600 text-white'
                      : item.category === 'CROP'
                      ? 'bg-emerald-600 text-white'
                      : 'bg-amber-600 text-white'
                  }`}
                >
                  {item.category}
                </span>
                <span className="text-[10px] font-bold text-slate-400">Target Action</span>
              </div>

              <button
                onClick={() => toggleActionComplete(item.id)}
                className={`flex items-center space-x-1.5 text-xs font-black px-3 py-1.5 rounded-xl transition-all ${
                  item.completed
                    ? 'bg-emerald-100 text-emerald-900'
                    : 'bg-slate-900 text-white hover:bg-slate-800'
                }`}
              >
                {item.completed ? (
                  <>
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span>Completed</span>
                  </>
                ) : (
                  <>
                    <Circle className="w-4 h-4 text-slate-400" />
                    <span>MARK COMPLETE</span>
                  </>
                )}
              </button>
            </div>

            <div>
              <h4 className={`font-black text-lg ${item.completed ? 'line-through text-slate-500' : 'text-slate-900'}`}>
                {item.title}
              </h4>
              <p className="text-xs text-slate-600 mt-1">Reason: <strong>{item.reason}</strong></p>
            </div>

            <div className="bg-slate-50 p-3.5 rounded-2xl border border-slate-200 text-xs text-slate-800 space-y-1">
              <span className="font-extrabold text-emerald-800">AI Recommended Procedure:</span>
              <p className="font-medium text-slate-700">{item.recommended}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
